/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-12 08:36:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>회원가입</title>\n");
      out.write("    <script>\n");
      out.write("    const cp = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("    </script>\n");
      out.write("<style>\n");
      out.write("	*{\n");
      out.write("		font-family: '123RF';\n");
      out.write("		font-size: 20px;\n");
      out.write("		color: white;\n");
      out.write("	}\n");
      out.write("    #wrap{\n");
      out.write("        width:600px;\n");
      out.write("        margin: 0 auto;\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("   body{\n");
      out.write("      background-color:rgb(11,18,19);\n");
      out.write("   }\n");
      out.write("   input{\n");
      out.write("      box-sizing: border-box;\n");
      out.write("      cursor:pointer;\n");
      out.write("   }\n");
      out.write("   table{\n");
      out.write("      border-collapse: collapse;\n");
      out.write("   }\n");
      out.write("   th{\n");
      out.write("      text-align: left;\n");
      out.write("   }\n");
      out.write("   th::after{\n");
      out.write("      content:\"\";\n");
      out.write("      display:inline-block;\n");
      out.write("      box-sizing:border-box;\n");
      out.write("      width:1px;\n");
      out.write("      height:14px;\n");
      out.write("      \n");
      out.write("   }\n");
      out.write("   th,td{\n");
      out.write("      padding:5px;\n");
      out.write("   }\n");
      out.write("   td{\n");
      out.write("      padding-left:20px;\n");
      out.write("      width:400px;\n");
      out.write("   }\n");
      out.write("   input[type=text], input[type=password], input[type=email],input[type=date],input[type=tel]{\n");
      out.write("      padding:10px 15px 10px 10px;\n");
      out.write("      border:1px solid #ccc;\n");
      out.write("      width:280px;\n");
      out.write("      color: navy;\n");
      out.write("   }\n");
      out.write("   input:focus{\n");
      out.write("      outline:none;\n");
      out.write("      border:1px solid rgb(0,200,80);\n");
      out.write("   }\n");
      out.write("  	#wrap>p:first-child{\n");
      out.write("  	text-align: center;\n");
      out.write("  	font-size: 30px;\n");
      out.write("  	margin-top: 20px;\n");
      out.write("  	}\n");
      out.write("   \n");
      out.write("   td > input[type=text]+input[type=button]{\n");
      out.write("      margin-left:10px;\n");
      out.write("      padding:8px 10px;\n");
      out.write("      background-color:rgb(50,50,50);\n");
      out.write("      color:#fff;\n");
      out.write("      font-size:14px;\n");
      out.write("      font-weight:bold;\n");
      out.write("      border:none;\n");
      out.write("      border-radius:5px;\n");
      out.write("      width:80px;\n");
      out.write("   }\n");
      out.write("      td > input[type=email]+input[type=button]{\n");
      out.write("      margin-left:10px;\n");
      out.write("      padding:8px 10px;\n");
      out.write("      background-color:rgb(50,50,50);\n");
      out.write("      color:#fff;\n");
      out.write("      font-size:14px;\n");
      out.write("      font-weight:bold;\n");
      out.write("      border:none;\n");
      out.write("      border-radius:5px;\n");
      out.write("      width:80px;\n");
      out.write("   }\n");
      out.write("   .gender_area > td{\n");
      out.write("      font-size:16px;\n");
      out.write("   }\n");
      out.write("   .zipcode_area > td > input[type=text]{\n");
      out.write("      width:200px;\n");
      out.write("   }\n");
      out.write("   .zipcode_area > td > input[type=button]{\n");
      out.write("      width:130px !important;\n");
      out.write("   }\n");
      out.write("   .addr_area > td > input[type=text], .addr_area+tr > td > input[type=text], .addr_area+tr+tr > td > input[type=text]{\n");
      out.write("      width:340px;\n");
      out.write("   }\n");
      out.write("   .hobby_area > td > div{\n");
      out.write("        display: flex;\n");
      out.write("      width:360px;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("   }\n");
      out.write("   .hobby_area > td > div > div{\n");
      out.write("      padding:10px;\n");
      out.write("      flex:1 1 40%;\n");
      out.write("   }\n");
      out.write("   .hobby_area > td > div > div:nth-child(2n){\n");
      out.write("      border-left:1px solid #ccc;\n");
      out.write("   }\n");
      out.write("   th input[type=submit]{\n");
      out.write("      margin:0 auto;\n");
      out.write("      padding:10px 10px;\n");
      out.write("      display : block;\n");
      out.write("      background-color:rgb(50,50,50);\n");
      out.write("      color:#fff;\n");
      out.write("      font-size:20px;\n");
      out.write("      font-weight:bold;\n");
      out.write("      border:none;\n");
      out.write("      border-radius:5px;\n");
      out.write("      width:200px;\n");
      out.write("   }\n");
      out.write("   #result{\n");
      out.write("      color:white;\n");
      out.write("      font-weight: bold;\n");
      out.write("   }\n");
      out.write("   #clone_proof{\n");
      out.write(" 	 position: absolute;\n");
      out.write("   visibility: hidden;\n");
      out.write("   }\n");
      out.write("	#proofchecktr{\n");
      out.write("	display: none;\n");
      out.write("	}\n");
      out.write("	#pwtxt{font-size: 15px;\n");
      out.write("	text-align: center;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index_join_login.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 <input type=\"hidden\" name=\"message\" id=\"message\" >\n");
      out.write("	     <video muted autoplay loop>\n");
      out.write("			 <source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/v.mp4\" type=\"video/mp4\" >\n");
      out.write("			 <strong>Your browser does not support the video tag.</strong>\n");
      out.write("		</video>\n");
      out.write("	<div id=\"black_box\"></div>\n");
      out.write("  <div id=\"clone_proof\">\n");
      out.write("    <form id=\"email_proof_form\">\n");
      out.write("        <label for=\"cloneusername\">cloneusername</label>\n");
      out.write("        <input type=\"text\" name=\"cloneusername\" id=\"cloneusername\">\n");
      out.write("        <label for=\"message\">message</label>\n");
      out.write("        <input type=\"text\" name=\"message\" id=\"message\">\n");
      out.write("        <label for=\"cloneemail\">cloneemail</label>\n");
      out.write("        <input type=\"text\" name=\"cloneemail\" id=\"cloneemail\">\n");
      out.write("      <input type=\"submit\" id=\"join_proof\" value=\"Send Email\" >\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("   <div id=\"wrap\">\n");
      out.write("  		<p> 회원가입 </p>\n");
      out.write("        <form name=\"joinForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/joinok.tc\" onsubmit=\"return sendit()\">\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <th><label for=\"userid\">아이디</label></th>\n");
      out.write("                    <td><input type=\"text\" name=\"userid\" id=\"userid\"><input type=\"button\" value=\"중복검사\" onclick=\"checkId()\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td id=\"result\" colspan=\"2\"></td>\n");
      out.write("                </tr>         \n");
      out.write("                <tr>\n");
      out.write("                    <th><label for=\"userpw\">비밀번호</label></th>\n");
      out.write("                    <td><input type=\"password\" name=\"userpw\" id=\"userpw\" onkeyup=\"pwcheck()\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th><label for=\"userpw_re\">비밀번호 확인</label></th>\n");
      out.write("                    <td><input type=\"password\" name=\"userpw_re\" id=\"userpw_re\" onkeyup=\"pwcheck()\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"2\"><span id=\"pwtxt\">비밀번호는 대문자와 소문자 특수문자를 넣은 8자 이상의 문자열입니다</span></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <th><label for=\"username\">이름</label></th>\n");
      out.write("                    <td><input type=\"text\" name=\"username\" id=\"username\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th><label for=\"useremail\">Email</label></th>\n");
      out.write("                    <td><input type=\"email\" name=\"useremail\" placeholder=\"이메일을 입력해 주세요\">\n");
      out.write("		                   <input type=\"button\" id=\"join_proof_btn\" value=\"인증하기\" onclick=\"proof()\">\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                	<tr id =\"proofchecktr\"> \n");
      out.write("                		<th><label for=\"useremail\">인증번호 입력</label></th>\n");
      out.write("                    <td><input type=\"text\" name=\"proofcheck\" placeholder=\"인증번호를 입력해 주세요\">\n");
      out.write("		                   <input type=\"button\" id=\"join_proofcheck_btn\" value=\"인  증\" onclick=\"proofcheckaction()\">\n");
      out.write("		                   <span id =\"proofok\"> &nbsp; </span>\n");
      out.write("                    </td>\n");
      out.write("                	</tr>\n");
      out.write("                	 <tr>\n");
      out.write("                    <th><label for=\"userphone\">핸드폰</label></th>\n");
      out.write("                    <td><input type=\"tel\" name=\"userphone\" placeholder=\"전화번호를 입력해주세요\">\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                	<tr class=\"birthday\"> \n");
      out.write("                			<th><label for=\"useremail\">생일</label></th>\n");
      out.write("                    <td> <input type=\"date\" name=\"userdob\">\n");
      out.write("                    </td>\n");
      out.write("                	</tr>\n");
      out.write("                <tr class=\"gender_area\">\n");
      out.write("                    <th>성별</th>\n");
      out.write("                    <td>\n");
      out.write("                        <label>남자 <input checked type=\"radio\" name=\"gender\" value=\"M\"></label>\n");
      out.write("                        <label>여자 <input type=\"radio\" name=\"gender\" value=\"W\"></label>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr class=\"zipcode_area\">\n");
      out.write("                    <th>우편번호</th>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\" name=\"zipcode\" readonly onclick=\"sample6_execDaumPostcode()\">\n");
      out.write("                        <input type=\"button\" value=\"우편번호 찾기\" onclick=\"sample6_execDaumPostcode()\">\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr class=\"addr_area\">\n");
      out.write("                    <th>주소</th>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" name=\"addr\" readonly>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>상세주소</th>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\" name=\"addrdetail\">\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th>참고항목</th>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\" name=\"addretc\" readonly>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <th colspan=\"2\">\n");
      out.write("                        <input type=\"submit\" value=\"가입 완료\">\n");
      out.write("                        <!-- <button></button> input:submit -->\n");
      out.write("                    </th>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("        <script type=\"text/javascript\"\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js\"></script>\n");
      out.write("          <script type=\"text/javascript\">\n");
      out.write("      emailjs.init('yVh6Vs9-C9j45EszD')\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cp }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/user.js\"></script>\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
